version: '2'
services:
  magentophp56:
     image: martonowibowo/centos6:php56
     volumes:
       - ".:/mnt"
     tty: true
     container_name: magento56
     networks:
      vpcbr:
        ipv4_address: 172.18.0.2

  magentophp70:
     image: martonowibowo/centos6:php70
     volumes:
     - ".:/mnt"
     tty: true
     container_name: magento70
     networks:
      vpcbr:
        ipv4_address: 172.18.0.3

  percona57:
     image: martonowibowo/centos6:percona57
     volumes:
     - ".:/mnt"
     tty: true
     container_name: percona57
     networks:
      vpcbr:
        ipv4_address: 172.18.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/24
         gateway: 172.18.0.1
