version: '3.3'
services:
  magentophp56:
     image: martonowibowo/centos6:php56
     volumes:
       - ".php56/nginx.conf:/etc/nginx/nginx.conf"
       - ".php56/sites-enabled:/etc/nginx/sites-enabled"
       - ".php56/php.ini:/etc/php.ini"
       - ".php56/www.conf:/etc/php-fpm.d/www.conf"
       - ".php56/nginx:/var/log/nginx"
     network_mode: bridge
     ports:
       - "80:80"
     tty: true
     container_name: magento56
