version: '2'
services:
  magentophp56:
     image: martonowibowo/centos6:php56
     volumes:
       - ".:/mnt"
     tty: true
     container_name: magento56

  magentophp70:
     image: martonowibowo/centos6:php70
     volumes:
     - ".:/mnt"
     tty: true
     container_name: magento70

  percona57:
     image: martonowibowo/centos6:percona57
     volumes:
     - ".:/mnt"
     tty: true
     container_name: percona57
